default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  database: <%= ENV.fetch("DATABASE_NAME", "redmine_development") %>
  username: <%= ENV.fetch("DATABASE_USER", "redmine") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "redmine_dev") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default

test:
  <<: *default
  database: redmine_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "redmine") %>